name: SecretSharingDotNet (All supported TFM)

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - '*'
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.415

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: .NET Core SxS
      run: |
        rsync -a ${DOTNET_ROOT/6.0.100/3.1.415}/* $DOTNET_ROOT/

    - name: Restore
      run: dotnet restore SecretSharingDotNet.sln

    - name: Build
      run: dotnet build --configuration Release SecretSharingDotNet.sln

    - name: Test
      run: dotnet test --configuration Release SecretSharingDotNet.sln

    - name: Prepare README.md for NuGet package
      run: |
           grep -n "## Install SecretSharingDotNet package" README.md | cut -d: -f 1| xargs -i tail -n +{} README.md > TMP.md && sed -i '1s/^/# Setup\r\n/' TMP.md && mv -f TMP.md README.md
           grep -n "# CLI building instructions" README.md | cut -d: -f 1| xargs -i head -n {} README.md | head -n -1 > TMP.md && mv -f TMP.md README.md

    - name: Create Package
      run: dotnet pack --configuration Release SecretSharingDotNet.sln
