name: SecretSharingDotNet .NET FX

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - '*'
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-2019
    
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest

      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\SecretSharingDotNetFx4.6.2.sln

      - name: Build with mbsuild
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe /p:Configuration=Release $Env:GITHUB_WORKSPACE\SecretSharingDotNetFx4.6.2.sln

      - name: Test with xUnit.net console runner
        run: |
           cd "$Env:GITHUB_WORKSPACE\packages\xunit.runner.console.2.4.1\tools\net462"
           .\xunit.console $Env:GITHUB_WORKSPACE\tests\bin\Release\SecretSharingDotNetTest.dll
