name: SecretSharingDotNet .NET

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - '*'
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        dotnet: [ '6.0.413', '7.0.400' ]
    name: Dotnet ${{ matrix.dotnet }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet SDK v6.0
      if: matrix.dotnet == '6.0.413'
      run: dotnet build --configuration Release SecretSharingDotNet6.sln
    - name: Test with dotnet SDK v6.0
      if: matrix.dotnet == '6.0.413'
      run: dotnet test --configuration Release SecretSharingDotNet6.sln
    - name: Build with dotnet SDK v7.0
      if: matrix.dotnet == '7.0.400'
      run: dotnet build --configuration Release SecretSharingDotNet7.sln
    - name: Test with dotnet SDK v7.0
      if: matrix.dotnet == '7.0.400'
      run: dotnet test --configuration Release SecretSharingDotNet7.sln
