name: SecretSharingDotNet (All supported TFM)

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - '*'
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.816

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.410

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301

    - name: .NET Core SxS
      run: |
        rsync -a ${DOTNET_ROOT/5.0.301/3.1.410/2.1.816}/* $DOTNET_ROOT/

    - name: Restore
      run: dotnet restore SecretSharingDotNet.sln

    - name: Build
      run: dotnet build --configuration Release SecretSharingDotNet.sln

    - name: Test
      run: dotnet test --configuration Release SecretSharingDotNet.sln

    - name: Create Package
      run: dotnet pack --configuration Release SecretSharingDotNet.sln
